### ISSUE TITLE
Composer app:test commands can't find simple-phpunit

### ISSUE THREAD

**Issue by florentdestremau** [strangebuzz/MicroSymfony#20]
On a fresh install, the example composer command doesn't work it seems. What is simple-phpunit ?

```
➜  microsymfony git:(master) composer app:test
> vendor/bin/simple-phpunit
sh: 1: vendor/bin/simple-phpunit: not found
Script vendor/bin/simple-phpunit handling the app:test event returned with error code 127
➜  microsymfony git:(master) 

```

**Comment by COil** [comment]
Hello @florentdestremau , yes you are right, I forgot to change the path after removing the Symfony phpunit bridge. 
Fixed by https://github.com/strangebuzz/MicroSymfony/commit/9fd1706f8b801bbe0abb317b1ecf163bebaee786  thanks  🙂
