### ISSUE TITLE
Bare.css less files are not needed and it's not required by the importmap (to be easier to remove)

### ISSUE THREAD

**Issue by florentdestremau** [strangebuzz/MicroSymfony#22]
For a boilerplate project, I would expect such dependencies to be very easy to remove, or at least to be minimal (pure css). 

![image](https://github.com/strangebuzz/MicroSymfony/assets/2852204/e9897344-2584-4ce6-a75a-6e63512b1332)

The right way would be to require them in the default assetmap
```
bin/console importmap:require barecss/css/style.min.css
```
and then include it in `assets/app.js` using

```
import './vendor/barecss/css/bare.min.css';
```

style.min.css does not seem to be available tho.

**Comment by COil** [comment]
Hello, can you submit a PR please ?
