### ISSUE TITLE
dx: Reset command

### ISSUE THREAD

**Issue by COil** [strangebuzz/MicroSymfony#25]
The goal would be to provide a "reset" command that would remove most of the demo code to keep only the very minimum. 

* The tests should still pass with a 100% coverage
* Keep only the app controller
* ...

**Comment by COil** [comment]
What do you think of this @florentdestremau  ?

**Comment by florentdestremau** [comment]
kind of like the create react app [eject](https://create-react-app.dev/docs/available-scripts#npm-run-eject) ? I don't know how you can maintain tests or any functions if you eject everything, it's the whole point of going back to an empty configuration. The test folders should be kept empty, but I can't see what you test.

**Comment by COil** [comment]
Yes, maybe it can be empty while keeping the directory structure. I'll give a try.
