### ISSUE TITLE
remove assets:compile from auto-scripts

### ISSUE THREAD

**Issue by tacman** [strangebuzz/MicroSymfony#6]
I spent way too long trying to figure out why my javascript wasn't working.  As soon as this command runs, the {{ asset() }} function returns _cached_ files.  It should only be run in a production environment.

I realize that this template currently defaults to the prod environment, but I think it should be 'dev', since as a template it's going to be changed and customized.

**Comment by COil** [comment]
OK, let's do this. I had the same probem when I pulled your code for the greet typo.

**Comment by COil** [comment]
You can do the PR :
* dev mode in .env file
* also add `APP_DEBUG=1`because it's better to be explicit about this parameter
* modify the deploy command of the Makefile to add the `asset-map:compile`

**Comment by COil** [comment]
Fixed by https://github.com/strangebuzz/MicroSymfony/commit/57869f6ff435d2be3d45be14dc8cc5adfa5894b2
